version: '2'
services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - PORT=3000
      - REDIS=redis_experiences
    depends_on:
      - redis_experiences
    links:
      - redis_experiences
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/experiences
    command: bash -c "bundle exec puma"
  redis_experiences:
    image: redis:3.0.7
    ports:
      - '6379:6379'

