version: '2'
services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
    depends_on:
      - experiences_redis
    links:
      - experiences_redis
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/experiences
    command: bash -c "bundle exec puma"
  experiences_redis:
    image: redis:3.0.7
    ports:
      - '6379:6379'
